name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: apt dependencies
      run: sudo apt install -y gcc gcc-multilib

    - name: test
      run: |
        make test
    - name: test 64
      run: |
        make test64

    - name: bench
      run: |
        make bench
    - name: bench 64
      run: |
        make bench64
